### ISSUE TITLE
ERROR protocol protocol.process_failure # [Failure instance: Traceback: <class '_mysql_exceptions.OperationalError'>: (1054, "Unknown column 'difficulty' in 'field list'")

### ISSUE THREAD

**Issue by litecoinmessiah** [moopless/stratum-mining-litecoin#24] opened 2013-06-28 11:12 UTC
I recieved this error:

None
2013-06-28 13:10:07,536 DEBUG protocol protocol.lineReceived # > {u'params': [u'benjamin.2', u'17', u'01000000', u'51cd6f09', u'9c551600'], u'id': 1054, u'method': u'mining.submit'}
2013-06-28 13:10:07,536 DEBUG DB_Mysql DB_Mysql.update_worker_diff # Setting difficulty for benjamin.2 to 16
2013-06-28 13:10:07,536 DEBUG DB_Mysql DB_Mysql.execute # MySQL connection lost during execute, attempting reconnect
2013-06-28 13:10:07,537 ERROR protocol protocol.process_failure # [Failure instance: Traceback: <class '_mysql_exceptions.OperationalError'>: (1054, "Unknown column 'difficulty' in 'field list'")
/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/protocol.py:192:dataReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/protocol.py:238:lineReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/services.py:13:_handle_event
/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/services.py:81:call
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:137:maybeDeferred
/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/services.py:78:_run
/home/pool/stratum-mining-litecoin/mining/service.py:94:submit
/home/pool/stratum-mining-litecoin/mining/interfaces.py:39:submit
/home/pool/stratum-mining-litecoin/mining/DBInterface.py:269:update_worker_diff
/home/pool/stratum-mining-litecoin/mining/DB_Mysql.py:259:update_worker_diff
/home/pool/stratum-mining-litecoin/mining/DB_Mysql.py:43:execute
/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py:174:execute
/usr/lib/python2.7/dist-packages/MySQLdb/connections.py:36:defaulterrorhandler
]
None
^C2013-06-28 13:10:09+0200 [-] SIGINT Detected, shutting down
2013-06-28 13:10:09,331 DEBUG DBInterface DBInterface.do_import # DBInterface.do_import called. force: yes, queue size: 0
2013-06-28 13:10:09,331 INFO DBInterface DBInterface.do_import # Inserting 0 Share Records
2013-06-28 13:10:09,331 DEBUG DB_Mysql DB_Mysql.import_shares # Importing Shares
2013-06-28 13:10:09+0200 [-](TCP Port 3335 Closed)
2013-06-28 13:10:09+0200 [-] Stopping factory <stratum.socket_transport.SocketTransportFactory instance at 0x30fad88>
2013-06-28 13:10:09,332 INFO stats stats.print_stats # 2 peers connected, state changed 1 times
2013-06-28 13:10:09,332 INFO stats stats.print_stats # 1 peers connected, state changed 1 times
2013-06-28 13:10:09,333 INFO stats stats.print_stats # 0 peers connected, state changed 1 times
2013-06-28 13:10:09+0200 [twisted.web.server.Site](TCP Port 8085 Closed)
2013-06-28 13:10:09+0200 [twisted.web.server.Site] Stopping factory <twisted.web.server.Site instance at 0x2f75488>
2013-06-28 13:10:09+0200 [-] Main loop terminated.
2013-06-28 13:10:09+0200 [-] Server Shut Down.
pool@server97:~/stratum-mining-litecoin$

I created tables for shares and pool worker using your sql code, viperaus code inserts fine btw, i even tried enabling vardiff and disabling it but did not help. Can you help please?

**Comment by moopless** [comment] 2013-06-28 12:07
Looks like you are missing the difficulty column. Can you paste the output from `desc shares;` and `desc pool_worker;` in mysql?

```
2013-06-28 13:10:07,537 ERROR protocol protocol.process_failure # [Failure instance: Traceback: : (1054, "Unknown column 'difficulty' in 'field list'")
```

**Comment by moopless** [comment] 2013-06-28 12:18
Looks like I was missing an alter statement in the sql file. I added it now. Please pull the new commit and try to run the mysql import again. 

Something like:
    mysql -u user -p database< sql/stratum_default_layout.sql

**Comment by moopless** [comment] 2013-06-28 18:23
Marking as a duplicate of #3

**Closed as completed by moopless** 2013-06-28 18:23 UTC
Labels: duplicate
