### ISSUE TITLE
Checking user & password doesn't work properly on PoS branch

### ISSUE THREAD

**Issue by svasva** [moopless/stratum-mining-litecoin#33] opened 2013-07-07 12:10 UTC
I guess it's getting cached somewhere so new users won't be able to connect until you restart the stratum server.

**Comment by feeleep75** [comment] 2013-07-08 11:23
i confirm

**Comment by moopless** [comment] 2013-07-08 12:06
I will be merging the memcache branch and PoS branch into stratum-lite. I will look at this when I do the merge.

**Comment by svasva** [comment] 2013-07-08 12:27
ouch. will it still work with PoW-only coins after that merge?

**Comment by moopless** [comment] 2013-07-08 12:31
I didn't mean offend anyone. The end goal is not to support multiple branches, but a single dynamic branch. It will have flags to turn on and off PoS, so it should still support PoW and PoS coins based on the settings. They will all be dependent on memcahced (and pylibmc).

Do you have the settings checking users passwords?

**Comment by svasva** [comment] 2013-07-08 12:32
Oh, that's nice.

Sure I had those settings enabled, and new users aren't enable to authorize until server restart. So I had to turn off worker authorization at all for now.

**Comment by obigal** [comment] 2013-07-16 12:58
On a POS coin I have a pool for, I'm sending the scrypt_hash to the shares table, none of the winning shares are marked 'Y' I'm using a recent version of php-mmcfe-ng and it's finding the correct shares via (stratum_blockhash) but again none are marked 'Y'

On a regular litecoin fork coin where I send in the block_hash_hex everything works as expected finding the correct shares via (stratum_blockhash) and they are marked 'Y' properly

I'm thinking I can change the POS coin back to block_hash and php-mmcfe-ng will find them via (stratum_solution) but haven't tried it yet I don't have the time right now to test it.

I just wanted to put a heads up if someone sends the scrypt_hash to the shares table they might not be marked correctly, I think it's looking for the block_hash_hex when trying to mark the winning share but a scrypt_hash_hex solution is in the table.

**Comment by obigal** [comment] 2013-07-16 13:05
Eh, my last post I though I was under the list of working Coins / changes for POS coin(s) issues. sorry

Oh, since I'm in the worker authorization issue shouldn't the password salt match what is in php-mmcfe-ng if your using that frontend?

**Comment by moopless** [comment] 2013-07-16 13:41
So for the PoS (all that I have seen) coins the block_hash == the
scrypt_hash. So in mmcfe-ng you should be able to set the block_hash flag
for any PoS coin. It could be something else that is stopping it from
updating the shares. My guess is the block check, which I need to remove in
this branch (I think)

 I found an issue with MySQL updates that may relate to this issue. I am
investigating today. I believe it is the cause for the restart for
authentication.

**Comment by obigal** [comment] 2013-07-16 17:05
Ok, I solved the non-marked shares, it was all me, my copy-paste skills are terrible.

**Comment by moopless** [comment] 2013-07-17 13:43
@obigal Glad to see things are working. 

@erundook and @feeleep75 Can you check to see if be351f8 resolves this issue? I was unable to reproduce it after making that change. It looks like python-mysqldb requires the changes to be committed before it will scan for the new record in the database. I enabled autocommit for this issue based on http://mysql-python.sourceforge.net/FAQ.html#my-data-disappeared-or-won-t-go-away

**Comment by feeleep75** [comment] 2013-07-17 20:45
it works for me

**Comment by moopless** [comment] 2013-07-17 20:53
@feeleep75 Thanks! I merged it in to the main and stratum-lite branches. In the previous comment I had the wrong commit id, so it has been updated. 

I'll go ahead and close this one out.

**Closed as completed by moopless** 2013-07-17 20:53 UTC
Labels: bug
